level: L2
owner: Jaden Li
classification: public
data_types:
  - name
  - email
  - phone
compliance:
  - none
review_history:
  - date: 2026-07-08
    reviewer: Security Reviewer
    review_level: L2
    verdict: FAIL
    score: 65
    findings_total: 7
    findings_open: 7
    tracking: JT-SEC-001 ~ JT-SEC-007
  - date: 2026-07-11
    reviewer: Security Reviewer
    review_level: L2
    verdict: PASS
    score: 100
    findings_total: 0
    findings_open: 0
  - date: 2026-07-11
    reviewer: Security Reviewer
    review_level: L2
    verdict: PASS
    score: 95
    findings_total: 3
    findings_open: 3
    tracking: JT-SEC-008 ~ JT-SEC-010
  - date: 2026-07-13
    reviewer: Security Reviewer
    review_level: L2
    verdict: PASS
    score: 90
    findings_total: 3
    findings_open: 3
    tracking: JT-SEC-008 ~ JT-SEC-010
  - date: 2026-07-14
    reviewer: Security Reviewer
    review_level: L2
    verdict: PASS
    score: 90
    findings_total: 3
    findings_open: 3
    tracking: JT-SEC-008 ~ JT-SEC-010
  - date: 2026-07-15
    reviewer: Security Reviewer
    review_level: L2
    verdict: PASS
    score: 85
    findings_total: 4
    findings_open: 4
    tracking: JT-SEC-008 ~ JT-SEC-011
  - date: 2026-07-16
    reviewer: Security Reviewer
    review_level: L2
    verdict: PASS
    score: 85
    findings_total: 4
    findings_open: 4
    tracking: JT-SEC-008 ~ JT-SEC-011
